# `.github/workflows/ci-cd.yml`
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint with ruff
        run: ruff check.
      - name: Test with pytest
        run: pytest

  build-and-push-docker:
    needs: test-and-lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push reco-service
        uses: docker/build-push-action@v4
        with:
          context:./apps/reco-service
          push: true
          tags: yourusername/reco-service:latest

  deploy-to-staging:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to K8s Staging
        # Logika untuk deploy menggunakan Helm ke cluster staging
        run: echo "Deploying to Staging..."